### ISSUE TITLE
Create checklist for project handoff for GSoC conclusion

### ISSUE THREAD

**Issue by willingc** [anitab-org/vms#111]
This issue is a checklist of items that I wish to review as we wrap up GSoC 2015 and prepare for Google Code In. @vubo: This is not a task list for you. It's a mental checklist for me, loosely influenced by 2 scoops of Django.

@vubo, @tapasweni-pathak, @rosariorobinson: feel free to add comments if you wish. 
## Code Style
-  [ ] flake8 tool applied to files (used to check pep8)
-  [ ] check and document code style
  - Line length:  79 for most lines; relax to 99 when readability is improved
  - avoid import \* and import order
  - Good, readable names
  - Short functions/methods
-  [ ] Add `from __future__ import absolute_import`
## Installation and environment
- [ ] review install instructions
- [ ] consider simplifications for environment
- [ ] consider simplifying local development environment (Docker, vagrant, virtualbox)
- [ ] automate where possible (scripts or tools)
- [ ] clarify requirements and dependencies
## Settings files, env settings, and keys
- [ ] review settings file for any unused apps
- [ ] security review of settings, env, and keys
- [ ] consider local dev, staging, and production
## Models
- [ ] review model definitions
- [ ] address issue re: User, roles and email
## API
- [ ] Future consideration for custom reporting
## Admin
- [ ] Review docs
- [ ] Review usability for admins and volunteers
## Tests
- [ ] Review tests (unit, automated, coverage)
- [ ] Consider future test strategy for python versions and django version upgrades (tox)
- [ ] Reporting of test results after PR submission
- [ ] Develop merge strategy for automated testing code from GSocC 2015 into this code base.
## Documentation

(I :heart: docs!)
- [ ] Encourage enhancements and keeping it simple and usable
## Security
- [ ] CSRF
- [ ] keys
- [ ] Turn off DEBUG in production
- [ ] careful with any user uploaded data
- [ ] change default admin url
- [ ] reference 2 scoops appendix checklist
## Conclusion

Wow, that's a lot to review much less develop! Some cute inspiration... :cat: :dog: :baby_chick: :turtle: :penguin: :bird: :snake:  

:clap: Bravo for getting things done. :ocean: :sunrise:

**Comment by Nerdylicious** [comment]
@willingc @rosariorobinson 

Is Systers applying/taking part in Google Code-In this year? If so I would really like to be a mentor this year (for whatever project).

**Comment by willingc** [comment]
@Nerdylicious I believe so. You would be a great mentor. I'm not involved in the details but I know @rosariorobinson will bring you up to speed.

On another note, @Nerdylicious, I would like to tag the VMS repo in github with a few releases:
- v0.1.0 initial proof of concept
- v0.2.0 start of GSoC 2015
- v0.3.0 demo of GSoC 2015

I could use your help deciding what commit would be best to tag for v0.1.0 dd57b73d4c0809d2b7e312b08952ae55ec4b71e3, v0.2.0 0190b907673f638c21ef3bc1673bfcc3c1a4735e would be my best guess. The reason that I would like to tag points in time is that I think its cool to see the progress made from time to time :smile:

**Comment by Nerdylicious** [comment]
@willingc the commit for v0.2.0 looks good. Maybe we could go a little further along for v0.1.0 such as f6532b1cf58845369b2bd79af9517f6fce5fef57 (this one is a month later at July 2014 and includes a few more core features).

**Comment by willingc** [comment]
@Nerdylicious Absolutely. I will tag the commit that you suggested :)

**Comment by tapasweni-pathak** [comment]
@willingc How much of this is done?
